# Generated by Django 4.0.6 on 2022-07-26 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogcomment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='timeStamp',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogcomment'),
        ),
    ]
